dist: trusty
sudo: false
language: python
python:
- '3.6'
git:
  depth: false
branches:
  only:
  - master
  - develop
  - /^[0-9]+/
stages:
  - name: testing
  - name: deploying

env:
  global:
  - THREADING_BACKEND=gevent
notifications:
  webhooks:
    urls:
    - secure: GQq5gi4oaDgJ6QQvNb1xnGMHlTzY38g/IePsURExefZi4AXUlaCbJOmR+XVZv+Dhz4GzSZ+BQ7WoWRZTu2wvyn/b/00JSieBmyMMobGSaNE1wjSdDTVTYnZV3TQgoHvlSQWpEPiuTFPVsvvbTkJgf2n5vtv+MsvkZHTHjsjtM4GC7Xi0ykzqiREsJlBf+mwqz5gsu7kVANeTtsBPBPEDM4ELhm5exa/fvvsw5N/9nmfFWkOTtZvVx03vacTJowZB2mIczmq6amdQ76ZwPAuzXsVTAT/vivBEEFm0Enicki2k3rj7JKdG+x2uerVsRGUHF3AbvI0Jcb/KOx7YtCgxU4KUDy0b6DdRn4uN72g3lt5eMhaOF9NP9DMIp0+4PSSQQRubuKgnHR5u40hbc2cz/sVaprrq4I+mTiubwaAwjD4AXMYOAqwTJ8DYwxHE1qo94w/bJ/FvNn+L0aTR/cWb0r002RDIGT0NPGm43Q3Me1VPA4o71bO/erllorvo5wuBRsPCHQinXBe9a1FVnkSd+MSxx5DXSG3p5HJnhKJTJLrJDLtDGVVVD8YOZEZDly4pli/27yAgoD6OcIaWdk0yGcPvzLaYgu4W8fdA1E6BTKnqq04lylUEeXKpXBzogeL1nlZBTxG6sIrVVSmXTTAH1Kt5I7kAiXt07V9o8kLmZAY=
    on_success: change
    on_failure: always

jobs:
  include:
    - stage: testing
      install:
      - pip install -c constraints.txt codecov
      - pip install -c constraints.txt -r requirements.txt
      - pip install -c constraints.txt -e .
      script:
      - flake8
      - mypy --ignore-missing-imports relay
      - ./pytest --cov=relay tests
      after_success:
      - codecov

    - stage: deploying
      name: docker
      sudo: true
      service: docker
      env:
        - DOCKER_USER=trustlinesautomation
        - secure: TMCObpO6yl9vW0Yp2skrRa9Exph5LO8aWniePHJKbldt3wKV+x7Ab0V2hD2/dZES85Pdqs7a1nSMOGMB60EZ9CiAr07LOZfltH7NsDuK+c5jqDffi+Wa8KW+CrNT/2lQ1Hz/eyVMHLUhUJEatUB4JzmhvaeRMkqRtkP+M6NaXub3mg9AFigr+aHZ/5Zl2l2z8CekAS4sLtrdcIR2cKYmUCJySpg9CVSM8VCOGouw+I7Y6QC6vn7MABGcpeUxsgdbUQag0xe5uBlTR6pOEp4UGHWC0kpvipNIdh8HhTECe9GhN0NltqL4HqBs1hsrnntta3bOFFjph/LljuWExo5X/w++Oy3p30wOuO7VSWjSPOXOiIFaADwlHzn08WerQextZmr/Q6c7VbH/BxJk/GMpG5CCvMCRUI4lON5zXLC6Z3N26w2PgA2cHnu792znInuVfW+qrGFVAo1owD9o18BBVlBJ1u4TjMr3viTy0enKJw7ksECg9Mh6mOtTiD+jhAZQlwH/eX0O3PbK3FQuu9p9x1O6OP3IKZIzGVJm3nS7jgqMYFONeHhoFKf7x1fPLfPbCSZrgu3tJnzxBFFAfi015uzUSk0mN9DALfTO04G7W9x4xxke8czn4EZyaFzP11zvft3T8VfQeh6fTTju+FEwRBgDiGyxRwO9okz31GYyQ0o=

      install: /bin/true
      script:
        - docker build -t relay .

      deploy:
        skip_cleanup: true
        provider: script
        script: ".travis/push-docker-image"
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^(develop|[0-9]+.*)$
    - stage: deploying
      name: pypi
      install: /bin/true
      script:
        - /bin/true
      deploy:
        - provider: pypi
          skip_cleanup: true
          user: trustlines
          password:
            secure: "tMorR/6c9+Rfqg1sRd7I5OitXe2QMZMH0O8NWaVD/DlZi/vNiSLA5ThzPUJRECpNCaUaUVvEQ/gR25gKuGoF2bInSQ1DUJtHM7U+snF/FFgcMdIR5Ppwun11SscZXYbaffhv5AGR9q0SuVuL9l09PTulCKqEU2Armr7NDLGib9v1+DKCS4pZ6gYYGCDEz24QFQ15ZiZFSXoOl+nG/2Lcced7RgIXb18mKpUhTM68FY4oMhbIAykyw4kg7NIcRTecq/8qR7G6S7pnuN4IbIJM2pvivRZAM/PjF+zzjf2DfDBg4r5yzZl33SUCkj3vW1v0M3VWvDpeCRQrjt7AyUKSOF6kTfm/sDehKyDJeQWguCzxDIVboUFWk5P5jODRFQyWvonglmvOxrLxG7Mmpi7t/MRZ2WRg6rf78jyLYoSyS3cE/s1gqdKygG2bCrO5EkktXl53ca1dZ7bWiSa/bak3nyGFb+wwtX2kZBFM2o9D0rcwsX6reHcb3aooHlPjPtG0OKO7umrL9BPaPV+hjUxzwZDRVL1VIaAMLeuFb6wKgJYBY03BM1bJh/A3SSrlMzXg+7MtjCMKq9CwKa1s87LKYGRuOCIsmh3adnENzQPBpicAti0E+qQGnQt2qKrwpC8oTiSXtqBklwGVqfq9l0whL0AvHHEY1XmojWtAXIOPwyA="
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH =~ ^([0-9]+.*)$
